- name: Configure systems with Docker, Kind and Kubectl
  hosts: hosts

  vars_files:
    - vars/secrets.yaml

  roles:
    - role: kubernetes_python
      tags: kubernetes_python
    - role: dkef_cluster
      tags: dkef_cluster
    - role: cert_manager
      tags: cert_manager
    - role: postgres_k8s
      tags: postgres_k8s
    - role: minio_k8s
      tags: minio_k8s
    - role: api_k8s
      tags: api_k8s
    - role: frontend_k8s
      tags: frontend_k8s