// <auto-generated />
using System;

using Dkef.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dkef_api.Migrations.Contents
{
    [DbContext(typeof(ContentsContext))]
    [Migration("20260404111703_ContentsInitialCreate")]
    partial class ContentsInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dkef.Domain.Abstracts.BaseContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contents", (string)null);

                    b.HasDiscriminator<string>("ContentType").HasValue("BaseContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dkef.Domain.Event", b =>
                {
                    b.HasBaseType("Dkef.Domain.Abstracts.BaseContent");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("Dkef.Domain.GeneralAssembly", b =>
                {
                    b.HasBaseType("Dkef.Domain.Abstracts.BaseContent");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GeneralAssembly");
                });

            modelBuilder.Entity("Dkef.Domain.News", b =>
                {
                    b.HasBaseType("Dkef.Domain.Abstracts.BaseContent");

                    b.HasDiscriminator().HasValue("News");
                });
#pragma warning restore 612, 618
        }
    }
}
