services:
  db:
    image: postgres:17.4
    container_name: postgres1
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=dkef
      - POSTGRES_DB=dkef
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - dkef-network

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    container_name: pgadmin1
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=don-sbn@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=mysecretpassword
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    volumes:
      - ./config/pgpassfile:/pgadmin4/pgpassfile
      - ./config/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - dkef-network

  minio:
    image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio1
    restart: on-failure
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"
    networks:
      - dkef-network

networks:
  dkef-network:
    external: true