- name: Install necessary packages to run DKEF
  hosts: hosts
  become: yes # Package installation requires root privileges, this escalates privileges

  tasks:
    - name: Update apt cache and install necessary packages for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker API repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker # This will create /etc/apt/sources.list.d/docker.list

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin # Optional
          - docker-compose-plugin # Optional
        state: present
        update_cache: yes # Update cache again after adding the new repo:

    - name: Ensure Docker service is running and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Create docker group if it doesn't exist
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add current user to the docker group
      # This task adds the ansible_user to the docker group.
      # Import: For this to take effect for interactive sessions,
      # the user will need to log out and back in, or run 'newgrp docker'.
      # Ansible itself will typically oprate with sudo, so it won't be affected immediately.
      ansible.builtin.user:
        name: "{{ ansible_user  }}"
        groups: docker
        append: yes