// <auto-generated />
using Dkef.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dkef.Migrations.AspNetRoles
{
    [DbContext(typeof(AspNetRolesContext))]
    partial class AspNetRolesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5a7892eb-6f59-4753-9ec4-3d173010647f",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            ConcurrencyStamp = "ca6e84e2-b7c4-4de6-be47-ee673fa69b69"
                        },
                        new
                        {
                            Id = "c6850c95-b8a1-4491-a52f-83b47b87b9cd",
                            Name = "Board Member",
                            NormalizedName = "BOARD MEMBER",
                            ConcurrencyStamp = "7f1a1f5a-3b14-434b-8647-7c5190f3f425"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
