- name: Check if kind is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/kind
  register: kind_executable_check

- name: Set kind download URL based on architecture
  ansible.builtin.set_fact:
    kind_download_url: >-
      https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-{{
      'arm64' if ansible_architecture == 'aarch64' else 'amd64'
      }}

- name: Download kind executable (if not installed)
  ansible.builtin.get_url:
    url: "{{ kind_download_url }}"
    dest: /tmp/kind
    mode: '0755' # Set executable permissions directly upon download
  when: not kind_executable_check.stat.exists

- name: Move kind to /usr/local/bin (if not installed)
  ansible.builtin.copy:
    src: /tmp/kind
    dest: /usr/local/bin/kind
    owner: root
    group: root
    mode: '0755'
    remote_src: yes # This is important as the source is on the remote machine
  when: not kind_executable_check.stat.exists
  notify: Clean up downloaded kind file

- name: Verify kind installation
  ansible.builtin.command: kind --version
  register: kind_version_check
  changed_when: false

- name: Display kind version
  ansible.builtin.debug:
    msg: "{{ kind_version_check.stdout }}"